apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: toba44/backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: mysql://root:rootpassword@database:3306/mydatabase
